name: Sync and Rebuild Blog

on:
  repository_dispatch:
    types: [obsidian_update]
  workflow_dispatch:

jobs:
  sync-and-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Download Obsidian content
        run: |
          # Replace with your Obsidian vault repo URL
          git clone https://github.com/dsvill06/blog_posts.git temp_vault
          cp -r temp_vault/path/to/notes/* data/blog/
          rm -rf temp_vault
        
      - name: Install dependencies
        run: npm install
        
      - name: Build site
        run: npm run build
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Auto-sync Obsidian content" || echo "No changes to commit"
          git push 