name: Trigger Blog Rebuild

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.mdx'
      - 'attachments/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog rebuild
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          https://api.github.com/repos/dsvill06/blog/dispatches \
          -d '{"event_type":"obsidian_update"}' 