name: Trigger Blog Rebuild

on:
  push:
    branches:
      - main  # or whatever your default branch is
    paths:
      - '**.md'
      - '**.mdx'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog rebuild
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          https://api.github.com/repos/dsvill06/YOUR_BLOG_REPO/dispatches \
          -d '{"event_type":"obsidian_update"}' 